reports:

    percent_interlanguage_navigation_curr:
        type: script
        granularity: weeks
        funnel: true
        starts: 2018-01-01
        lag: 86400 # wait 1 day to compute last week

    percent_interlanguage_navigation_prev:
        type: script
        granularity: weeks
        funnel: true
        starts: 2018-01-01
        lag: 86400 # wait 1 day to compute last week
